### ISSUE TITLE
Deleting Full Directories?

### ISSUE THREAD

**Issue by vector-man** [bradwestness/dossier-dot-net#1]
It would be nice if you could delete a full directory.

**Comment by bradwestness** [comment]
The default behavior is to call Directory.Delete() with the `recursive` parameter set to `true`. Are you getting an exception?

**Comment by vector-man** [comment]
Strange. I Was getting a "directory is not empty" exception. But it appears to be random. I'll try to see if I can find out what reproduced it.

Thank you for the reply!

**Comment by vector-man** [comment]
It looks like it only happens when I'm stepping through the debugger.  Disabling the breakpoints, it hasn't happened. I'll keep you updated if it happens again. Thanks!

**Comment by bradwestness** [comment]
That's super nutty! Keep me posted, thanks!
